
# The simulation control file is used to specify all input data
# for a simulation.
# It can also specify graph output types.
# CLI args overwrite the simulation control values.

[simulation]
input_data_file_path = "example-data/entities.csv"
cl_kernels_file_path = "example-data/cl-kernels.toml"

num_steps = 100
#preferred_gpu_name = "nvidia"

# These are required for graphical output that shows the positions of items
gis_x_attr_name = "X0"
gis_y_attr_name = "Y0"

# This is optional and allows GUI labeling; if unspecified the row index will be used (ie 0, 1, 2, 3...N for all N rows of input_data_file_path)
gis_name_attr = "Name"


# TODO would it make sense to expose some kind of data_constants['constant_name'] range
# definition here? This would expose parametric capabilities to a single simulation.

[data_constants]
#entity_speed_coef = 1.5

